[package]
name = "multiworld"
version = "0.1.0"
edition = "2021"

[dependencies]
async-proto = "0.15"
async-recursion = "1"
chrono = "0.4"
itertools = "0.10"
thiserror = "1"

[dependencies.tokio]
version = "1"
features = ["net", "sync"]
