[package]
name = "multiworld"
version = "0.1.0"
edition = "2021"

[dependencies]
async-recursion = "1"
chrono = "0.4"

[dependencies.async-proto]
version = "0.12"
features = ["blocking"]

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.tokio]
version = "1"
features = ["net", "sync"]
