[package]
name = "multiworld-installer"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "4"
itertools = "0.10"
lazy-regex = "2"
nfd2 = "0.3"
thiserror = "1"

[dependencies.iced]
version = "0.3"
features = ["tokio"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json", "rustls-tls", "trust-dns"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["rt-multi-thread"]

[dependencies.url]
version = "2"
features = ["serde"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
