[package]
name = "multiworld-csharp"
version = "0.1.0"
edition = "2021"

[lib]
name = "multiworld"
crate-type = ["cdylib"]

[dependencies]
async-proto = "0.15"
itertools = "0.10"
libc = "0.2"

[dependencies.multiworld]
path = "../multiworld"
