[package]
name = "multiworld-csharp"
version = "0.1.0"
edition = "2021"

[lib]
name = "multiworld"
crate-type = ["cdylib"]

[dependencies]
itertools = "0.10"
libc = "0.2"

[dependencies.async-proto]
version = "0.10.0"
features = ["blocking"]

[dependencies.multiworld]
path = "../multiworld"
